# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct TagsApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `TagsApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ TagsApi }) = "http://localhost"

const _returntypes_create_a_new_tag_TagsApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => SubscriberTag,
)

function _oacinternal_create_a_new_tag(_api::TagsApi; subscriber_tag=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_a_new_tag_TagsApi, "/v1/tags", [], subscriber_tag)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/x-www-form-urlencoded", "multipart/form-data", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- subscriber_tag::SubscriberTag

Return: SubscriberTag, OpenAPI.Clients.ApiResponse
"""
function create_a_new_tag(_api::TagsApi; subscriber_tag=nothing, _mediaType=nothing)
    _ctx = _oacinternal_create_a_new_tag(_api; subscriber_tag=subscriber_tag, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_a_new_tag(_api::TagsApi, response_stream::Channel; subscriber_tag=nothing, _mediaType=nothing)
    _ctx = _oacinternal_create_a_new_tag(_api; subscriber_tag=subscriber_tag, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_a_tag_TagsApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_delete_a_tag(_api::TagsApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_a_tag_TagsApi, "/v1/tags/{id}", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, [])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::String (required)

Return: Nothing, OpenAPI.Clients.ApiResponse
"""
function delete_a_tag(_api::TagsApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_a_tag(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_a_tag(_api::TagsApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_a_tag(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_all_tags_TagsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ListAllTags200Response,
)

function _oacinternal_list_all_tags(_api::TagsApi; page=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_all_tags_TagsApi, "/v1/tags", [])
    OpenAPI.Clients.set_param(_ctx.query, "page", page)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- page::Int64

Return: ListAllTags200Response, OpenAPI.Clients.ApiResponse
"""
function list_all_tags(_api::TagsApi; page=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_all_tags(_api; page=page, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_all_tags(_api::TagsApi, response_stream::Channel; page=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_all_tags(_api; page=page, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_partially_update_an_existing_tag_TagsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SubscriberTag,
)

function _oacinternal_partially_update_an_existing_tag(_api::TagsApi, id::String; subscriber_tag=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PATCH", _returntypes_partially_update_an_existing_tag_TagsApi, "/v1/tags/{id}", [], subscriber_tag)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/x-www-form-urlencoded", "multipart/form-data", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::String (required)
- subscriber_tag::SubscriberTag

Return: SubscriberTag, OpenAPI.Clients.ApiResponse
"""
function partially_update_an_existing_tag(_api::TagsApi, id::String; subscriber_tag=nothing, _mediaType=nothing)
    _ctx = _oacinternal_partially_update_an_existing_tag(_api, id; subscriber_tag=subscriber_tag, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function partially_update_an_existing_tag(_api::TagsApi, response_stream::Channel, id::String; subscriber_tag=nothing, _mediaType=nothing)
    _ctx = _oacinternal_partially_update_an_existing_tag(_api, id; subscriber_tag=subscriber_tag, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_retrieve_an_existing_tag_TagsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SubscriberTag,
)

function _oacinternal_retrieve_an_existing_tag(_api::TagsApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_retrieve_an_existing_tag_TagsApi, "/v1/tags/{id}", [])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::String (required)

Return: SubscriberTag, OpenAPI.Clients.ApiResponse
"""
function retrieve_an_existing_tag(_api::TagsApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_retrieve_an_existing_tag(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function retrieve_an_existing_tag(_api::TagsApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_retrieve_an_existing_tag(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_an_existing_tag_TagsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SubscriberTag,
)

function _oacinternal_update_an_existing_tag(_api::TagsApi, id::String; subscriber_tag=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_an_existing_tag_TagsApi, "/v1/tags/{id}", [], subscriber_tag)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", "application/x-www-form-urlencoded", "multipart/form-data", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- id::String (required)
- subscriber_tag::SubscriberTag

Return: SubscriberTag, OpenAPI.Clients.ApiResponse
"""
function update_an_existing_tag(_api::TagsApi, id::String; subscriber_tag=nothing, _mediaType=nothing)
    _ctx = _oacinternal_update_an_existing_tag(_api, id; subscriber_tag=subscriber_tag, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_an_existing_tag(_api::TagsApi, response_stream::Channel, id::String; subscriber_tag=nothing, _mediaType=nothing)
    _ctx = _oacinternal_update_an_existing_tag(_api, id; subscriber_tag=subscriber_tag, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_a_new_tag
export delete_a_tag
export list_all_tags
export partially_update_an_existing_tag
export retrieve_an_existing_tag
export update_an_existing_tag
