# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

module APIClient

using Dates, TimeZones
using OpenAPI
using OpenAPI.Clients

const API_VERSION = "1.0.0"

include("modelincludes.jl")

include("apis/api_DraftsApi.jl")
include("apis/api_EmailsApi.jl")
include("apis/api_ImagesApi.jl")
include("apis/api_MiscellanyApi.jl")
include("apis/api_NewslettersApi.jl")
include("apis/api_ScheduledEmailsApi.jl")
include("apis/api_SubscribersApi.jl")
include("apis/api_TagsApi.jl")
include("apis/api_UnsubscribersApi.jl")

end # module APIClient
