# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

include("models/model_Draft.jl")
include("models/model_Email.jl")
include("models/model_ListAllDrafts200Response.jl")
include("models/model_ListAllEmails200Response.jl")
include("models/model_ListAllNewsletters200Response.jl")
include("models/model_ListAllScheduledEmails200Response.jl")
include("models/model_ListAllSubscribers200Response.jl")
include("models/model_ListAllTags200Response.jl")
include("models/model_ListAllUploadedImages200Response.jl")
include("models/model_ListUnsubscribers200Response.jl")
include("models/model_Newsletter.jl")
include("models/model_ScheduledEmail.jl")
include("models/model_Subscriber.jl")
include("models/model_SubscriberTag.jl")
include("models/model_UploadedImage.jl")
