name = "Buttondown"
uuid = "c4f6d564-31f0-4691-ab41-c66af6137b41"
authors = ["Jacob Zelko <jacobszelko@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
OpenAPI = "d5e62ea6-ddf3-4d43-8e4c-ad5e6c8bfd7d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
