# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""List_all_newsletters_200_response

    ListAllNewsletters200Response(;
        count=nothing,
        next=nothing,
        previous=nothing,
        results=nothing,
    )

    - count::Int64
    - next::String
    - previous::String
    - results::Vector{Newsletter}
"""
Base.@kwdef mutable struct ListAllNewsletters200Response <: OpenAPI.APIModel
    count::Union{Nothing, Int64} = nothing
    next::Union{Nothing, String} = nothing
    previous::Union{Nothing, String} = nothing
    results::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Newsletter} }

    function ListAllNewsletters200Response(count, next, previous, results, )
        OpenAPI.validate_property(ListAllNewsletters200Response, Symbol("count"), count)
        OpenAPI.validate_property(ListAllNewsletters200Response, Symbol("next"), next)
        OpenAPI.validate_property(ListAllNewsletters200Response, Symbol("previous"), previous)
        OpenAPI.validate_property(ListAllNewsletters200Response, Symbol("results"), results)
        return new(count, next, previous, results, )
    end
end # type ListAllNewsletters200Response

const _property_types_ListAllNewsletters200Response = Dict{Symbol,String}(Symbol("count")=>"Int64", Symbol("next")=>"String", Symbol("previous")=>"String", Symbol("results")=>"Vector{Newsletter}", )
OpenAPI.property_type(::Type{ ListAllNewsletters200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListAllNewsletters200Response[name]))}

function check_required(o::ListAllNewsletters200Response)
    true
end

function OpenAPI.validate_property(::Type{ ListAllNewsletters200Response }, name::Symbol, val)
    if name === Symbol("next")
        OpenAPI.validate_param(name, "ListAllNewsletters200Response", :format, val, "uri")
    end
    if name === Symbol("previous")
        OpenAPI.validate_param(name, "ListAllNewsletters200Response", :format, val, "uri")
    end
end
