# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Draft

    Draft(;
        body=nothing,
        creation_date=nothing,
        id=nothing,
        modification_date=nothing,
        subject=nothing,
    )

    - body::String
    - creation_date::ZonedDateTime
    - id::String
    - modification_date::ZonedDateTime
    - subject::String
"""
Base.@kwdef mutable struct Draft <: OpenAPI.APIModel
    body::Union{Nothing, String} = nothing
    creation_date::Union{Nothing, ZonedDateTime} = nothing
    id::Union{Nothing, String} = nothing
    modification_date::Union{Nothing, ZonedDateTime} = nothing
    subject::Union{Nothing, String} = nothing

    function Draft(body, creation_date, id, modification_date, subject, )
        OpenAPI.validate_property(Draft, Symbol("body"), body)
        OpenAPI.validate_property(Draft, Symbol("creation_date"), creation_date)
        OpenAPI.validate_property(Draft, Symbol("id"), id)
        OpenAPI.validate_property(Draft, Symbol("modification_date"), modification_date)
        OpenAPI.validate_property(Draft, Symbol("subject"), subject)
        return new(body, creation_date, id, modification_date, subject, )
    end
end # type Draft

const _property_types_Draft = Dict{Symbol,String}(Symbol("body")=>"String", Symbol("creation_date")=>"ZonedDateTime", Symbol("id")=>"String", Symbol("modification_date")=>"ZonedDateTime", Symbol("subject")=>"String", )
OpenAPI.property_type(::Type{ Draft }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Draft[name]))}

function check_required(o::Draft)
    o.body === nothing && (return false)
    o.subject === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ Draft }, name::Symbol, val)
    if name === Symbol("creation_date")
        OpenAPI.validate_param(name, "Draft", :format, val, "date-time")
    end
    if name === Symbol("id")
        OpenAPI.validate_param(name, "Draft", :format, val, "uuid")
    end
    if name === Symbol("modification_date")
        OpenAPI.validate_param(name, "Draft", :format, val, "date-time")
    end
end
